In [69]:
print("Hello Neemo!")

Hello Neemo!

In [70]:
import pandas as pd
import matplotlib.pyplot as plt
import sys
from pathlib import Path 
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.append(str(project_root)) 
from utils.data_cleaning import *
from config.settings import (
    FEATURE_REGEX_PATTERNS,
    FUNC_CLEAN_DICT,
    OHE_FEATURES,
    OHE_METADATA_FILE_POWER,
    OUTPUT_FILE_POWER,
    PROCESSED_FILE_POWER,
)

In [71]:
df_raw = pd.read_csv(r"D:\IMP  ML  PROJECTS\second-hand-car-features-predicion\predictions\data\power\raw\data.csv")
df_raw.head()

,Engine,No. of Cylinders,Drive Type,Transmission,Fuel Type,Engine Type,Emission Norm Compliance,Valves Per Cylinder,Power
0,2755 cc,4.0,4WD,Automatic,Diesel,2.8 L Diesel engine,BS VI,4.0,201.15 bhp
1,1086 cc,4.0,FWD,Manual,Petrol,IRDE2 Engine,BSIV,3.0,68.05 bhp
2,2179 cc,4.0,AWD,Manual,Diesel,2.2 LTR. VARICOR 400,BS IV,4.0,153.86 bhp
3,2198 cc,4.0,AWD,Automatic,Diesel,mHAWK,BS VI 2.0,4.0,182 bhp
4,2179 cc,4.0,FWD,Manual,Diesel,mHawk Diesel Engine,BS IV,4.0,152.87 bhp

In [84]:
df = pd.read_csv(r"D:\IMP  ML  PROJECTS\second-hand-car-features-predicion\predictions\data\power\processed\data.csv")
df.head()

,Engine,No. of Cylinders,Fuel Type,Emission Norm Compliance,Valves Per Cylinder,Power,engine_shape,engine_volume,Transmission_1,Drive Type_FWD,Drive Type_RWD
0,2755.0,4.0,Diesel,6,4.0,201.15,Unknown,2.8L,1,0,0
1,1086.0,4.0,Petrol,4,3.0,68.05,Unknown,Unknown,0,1,0
2,2179.0,4.0,Diesel,4,4.0,153.86,Unknown,2.2L,0,0,0
3,2198.0,4.0,Diesel,7,4.0,182.00,Unknown,Unknown,1,0,0
4,2179.0,4.0,Diesel,4,4.0,152.87,Unknown,Unknown,0,1,0

In [86]:
df['engine_volume'].value_counts()

engine_volume
Unknown    1485
1.5L        174
1.2L        167
2.0L        131
1.0L         97
3.0L         20
1.4L         15
2.2L         13
1.1L         11
2.8L         10
0.8L          9
2.7L          8
2.5L          7
2.4L          6
5.0L          5
1.3L          5
1.8L          4
4.0L          3
2.6L          1
3.6L          1
3.5L          1
1.6L          1
5.2L          1
Name: count, dtype: int64

In [1]:
from catboost import CatBoostRegressor

AttributeError: module 'pyarrow' has no attribute '__version__'